docker-compose-yaml: docker-compose.yml

project: lumen-example #TODO: ADD YOUR PROJECT NAME
endpoint: api-lagoon-master.lagoon.ch.amazee.io:31472
api: api-lagoon-master.lagoon.ch.amazee.io:80

tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
#environments:
#  master:
#    cronjobs:
#      - name: cronjob
#        schedule: "*/15 * * * *"
#        command: 
#        service: cli
